services:
  mongo:
    image: mongo
    container_name: mongodb
    ports : 
      - "27017:27017"

  rabbitmq-node:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-node
    ports:
      - "5672:5672"
      - "15672:15672"
      
  task-service:
    build: "./task-service"
    container_name: task-service
    ports:
      - "3001:3001"
    depends_on: 
      - rabbitmq-node
      - mongo

  user-service:
    build: "./user-service"
    container_name: user-service
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  notification-service:
    build : "./notification-service"
    container_name: notification-service
    ports:
      - "3002:3002"
    depends_on: 
      - rabbitmq-node